"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {useSearchParams} from "next/navigation";
import {BackgroundJob,getBackgroundJob,getProjects,Project,MetaDescriptionPreview,previewMetaDescriptionSitemap,importMetaDescriptionFile,startMetaDescriptionAuditJob,getMetaDescriptionAudits,MetaDescriptionReport,IndexingImportResult} from "@/lib/api";import {BackgroundJobCard} from "@/components/background-job-card";
export default function MetaDescriptionsPage(){const params=useSearchParams();const [projects,setProjects]=useState<Project[]>([]),[pid,setPid]=useState<number|"">(""),[mode,setMode]=useState("sitemap"),[sitemap,setSitemap]=useState(""),[preview,setPreview]=useState<MetaDescriptionPreview|null>(null),[selected,setSelected]=useState<string[]>([]),[include,setInclude]=useState(""),[exclude,setExclude]=useState(""),[manual,setManual]=useState(""),[file,setFile]=useState<File|null>(null),[importInfo,setImportInfo]=useState<IndexingImportResult|null>(null),[column,setColumn]=useState(""),[job,setJob]=useState<BackgroundJob|null>(null),[history,setHistory]=useState<MetaDescriptionReport[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
useEffect(()=>{Promise.all([getProjects(),getMetaDescriptionAudits()]).then(([p,h])=>{setProjects(p);setHistory(h);const q=Number(params.get("project"));setPid(q&&p.some(x=>x.id===q)?q:(p[0]?.id??""))}).catch(e=>setError(e.message))},[]);
useEffect(()=>{if(!job||!(job.status==="queued"||job.status==="running"))return;const t=setInterval(async()=>{const n=await getBackgroundJob(job.id);setJob(n);if(n.status==="completed")setHistory(await getMetaDescriptionAudits())},1200);return()=>clearInterval(t)},[job?.id,job?.status]);
const project=useMemo(()=>projects.find(x=>x.id===pid),[projects,pid]);
const filtered=useMemo(()=>{const src=preview?.urls??selected;return src.filter(u=>(!include||include.split("\n").filter(Boolean).every(x=>u.includes(x.trim())))&&(!exclude||exclude.split("\n").filter(Boolean).every(x=>!u.includes(x.trim()))))},[preview,selected,include,exclude]);
async function getSitemap(){if(!pid)return;setLoading(true);setError("");try{const p=await previewMetaDescriptionSitemap(pid,sitemap);setPreview(p);setSelected(p.urls)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
async function getFile(chosen=""){if(!pid||!file)return;setLoading(true);try{const r=await importMetaDescriptionFile(pid,file,chosen);setImportInfo(r);setColumn(r.selected_column||r.detected_column||"");setPreview(null);setSelected(r.needs_column?[]:r.urls)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
function getManual(){const urls=manual.split(/[\s,;]+/).map(x=>x.trim()).filter(x=>/^https?:\/\//i.test(x));setPreview(null);setSelected([...new Set(urls)])}
async function run(){if(!pid||!filtered.length)return;setJob(await startMetaDescriptionAuditJob({project_id:pid,urls:filtered,source_name:mode==="sitemap"?"Карта сайта":mode==="file"?(file?.name||"Файл"):"Ручной список",sitemap_url:preview?.sitemap_url||sitemap}))}
return <><header className="topbar"><div><Link href="/audit" className="taskBack">← SEO-аудит</Link><span className="eyebrow">Массовая проверка</span><h1>Аудит Meta Description</h1><p>Получить URL → выбрать раздел → проверить Description → исправлять только нужные страницы.</p></div><Link href="/jobs" className="button dark">Фоновые процессы →</Link></header>
<section className="descSource"><div className="descTabs">{[["sitemap","Карта сайта"],["file","XLSX / CSV"],["manual","Ручной список"]].map(([k,l])=><button className={mode===k?"active":""} onClick={()=>setMode(k)} key={k}>{l}</button>)}</div><div className="descSourceBody"><label>Проект<select value={pid} onChange={e=>{setPid(Number(e.target.value));setPreview(null);setSelected([])}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{mode==="sitemap"&&<><label className="wide">Домен или адрес карты сайта<input value={sitemap} onChange={e=>setSitemap(e.target.value)} placeholder={project?.sitemap_url||project?.domain||"https://example.ru/"}/></label><button className="button primary" onClick={getSitemap} disabled={loading}>{loading?"Ищу…":"Найти карту сайта"}</button></>}{mode==="file"&&<><label className="wide">Файл<input type="file" accept=".xlsx,.csv" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="button primary" onClick={()=>getFile()} disabled={!file||loading}>Получить URL</button></>}{mode==="file"&&importInfo?.needs_column&&<div className="indexingColumnPicker"><div><strong>Выберите колонку URL</strong><p>Автоматически определить её не удалось.</p></div><select value={column} onChange={e=>setColumn(e.target.value)}><option value="">Колонка…</option>{importInfo.columns.map(x=><option value={x} key={x}>{x}</option>)}</select><button className="button" disabled={!column} onClick={()=>getFile(column)}>Использовать</button></div>}{mode==="manual"&&<><label className="wide">URL по одному в строке<textarea rows={6} value={manual} onChange={e=>setManual(e.target.value)}/></label><button className="button primary" onClick={getManual}>Применить</button></>}</div></section>
{preview&&<section className="descPreview"><div className="sectionHead"><div><h2>Предпросмотр URL</h2><p>Аудит ещё не запущен.</p></div></div><div className="descKpis"><div><span>Найдено карт сайта</span><strong>{preview.sitemaps_count}</strong></div><div><span>URL найдено</span><strong>{preview.found_urls}</strong></div><div><span>Уникальных</span><strong>{preview.unique_urls}</strong></div><div><span>Дублей</span><strong>{preview.duplicates}</strong></div></div><div className="descSections">{Object.entries(preview.sections).map(([s,c])=><button key={s} onClick={()=>setInclude(s)}><b>{s}</b><span>{c}</span></button>)}</div></section>}
{selected.length>0&&<section className="descFilters"><div><label>URL содержит<textarea rows={3} value={include} onChange={e=>setInclude(e.target.value)} placeholder="/catalog/"/></label><label>URL не содержит<textarea rows={3} value={exclude} onChange={e=>setExclude(e.target.value)} placeholder="/news/"/></label></div><div className="descRun"><strong>{filtered.length}</strong><span>URL будут проверены</span><button className="button primary" onClick={run}>Проверить Description</button></div></section>}
{error&&<div className="auditError">{error}</div>}{job&&<section className="currentJobSection"><BackgroundJobCard job={job} onChange={setJob}/></section>}
<section><div className="sectionHead"><div><h2>Предыдущие аудиты</h2></div></div><div className="indexingHistory">{history.map(r=><Link href={`/audit/descriptions/${r.id}`} key={r.id} className="indexingHistoryRow"><div><strong>{r.project_name}</strong><span>{r.source_name} · {r.created_at}</span></div><div className="indexingHistoryStats"><span className="indexingStatus ok">{r.ok_count} Всё в порядке</span><span className="indexingStatus content">{r.review_count} Проверить</span><span className="indexingStatus developer">{r.replace_count} Исправить</span>{r.technical_count>0&&<span className="indexingStatus insufficient">{r.technical_count} Технические</span>}</div><b>{r.urls_total} URL →</b></Link>)}</div></section></>}
